# Generated by Django 5.0.1 on 2024-01-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiskar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='fish_type',
            field=models.CharField(choices=[('svärdfisk', 'Svärdfisk'), ('clownfisk', 'Clownfisk'), ('bläckfisk', 'Bläckfisk'), ('blåsfisk', 'Blåsfisk')], max_length=20),
        ),
    ]
