# Generated by Django 5.0.1 on 2024-01-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiskar', '0002_alter_fish_fish_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='title',
            field=models.TextField(default='Title', max_length=30),
        ),
    ]
