# Generated by Django 5.0.1 on 2024-01-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiskar', '0003_fish_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
