# Generated by Django 5.0.1 on 2024-02-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiskar', '0004_alter_like_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='name',
            field=models.TextField(default='Namn', max_length=30),
        ),
    ]
